version: '3.6'
services:
  odoo:
    build: .
    command: odoo -d odoo -i jsd_contacts -u jsd_contacts --dev xml --log-level=debug --logfile=/dev/stdout
    ports:
      - 8069:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - .:/mnt/extra-addons/jsd_contacts
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
